image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      go mod tidy
      pnpm install
    command: |
      wails dev

ports:
  - port: 34115
    onOpen: open-preview

vscode:
  extensions:
    - svelte.svelte-vscode
    - golang.go
    - bradlc.vscode-tailwindcss